volumes:
  static:
  media:
  pg_data:
  redoc:


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  backend:
    build: ./backend/
    env_file: .env

    volumes:
      - static:/backend_static
      - media:/media

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
