# Generated by Django 3.2.3 on 2024-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(choices=[('кг', 'кг'), ('гр', 'гр')], max_length=64, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.SmallIntegerField(verbose_name='Время готовки'),
        ),
    ]
